# Use an official Ubuntu base image
FROM ubuntu:24.04

# Set environment variables
ENV DEBIAN_FRONTEND=noninteractive

# Create a non-root user
RUN useradd -m -s /bin/bash user && \
    mkdir -p /var/dbdata && \
    chown -R user:user /var/dbdata

# Update and install necessary packages
RUN apt-get update && apt-get install -y \
    curl \
    git \
    golang \
    sudo \
    postgresql \
    postgresql-contrib

RUN echo "user ALL=(ALL) NOPASSWD:ALL" >> /etc/sudoers

# Install Node.js and npm using NodeSource
RUN curl -fsSL https://deb.nodesource.com/setup_lts.x | bash - && \
    apt-get install -y nodejs

# Install the latest version of npm
RUN npm install -g npm@latest

# Clean up
RUN apt-get clean && rm -rf /var/lib/apt/lists/*

# Set the working directory and change ownership
WORKDIR /app
COPY --chown=user:user client/ client/
COPY --chown=user:user server/ server/
COPY --chown=user:user db.sh .
RUN chown user:user /app

# Add build arguments
ARG SQUARE_LOCATION_ID
ARG SQUARE_APP_ID

# Build the UI
WORKDIR /app/client
RUN npm install
RUN REACT_APP_SQUARE_LOCATION_ID=${SQUARE_LOCATION_ID} REACT_APP_SQUARE_APP_ID=${SQUARE_APP_ID} npm run build

# Build the server
WORKDIR /app/server
RUN go mod download
RUN GOFLAGS=-buildvcs=false go build -o server

# Expose the default port
EXPOSE 8080

# Copy the database script and make it executable
WORKDIR /app
COPY prod.sh /app/prod.sh
RUN chmod +x /app/db.sh
RUN chmod +x /app/prod.sh

# Switch to non-root user
USER user

# Change the CMD to use the startup script
CMD ["/app/prod.sh"]

# Docker build command to use:
#    docker build \
#    --build-arg SQUARE_LOCATION_ID=your_location_id \
#    --build-arg SQUARE_APP_ID=your_app_id \
#    -t languagelearn-deploy .
    
# Docker run command to use:
# docker run -d \
#   --name languagelearn \
#   --network host \
#   -v /path/to/local/dbdata:/var/dbdata \
#   -e OPENAI_SECRET_KEY \
#   -e GOOGLE_API_SECRET \
#   -e SQUARE_APP_ID \
#   -e SQUARE_LOCATION_ID \
#   -e SQUARE_ACCESS_TOKEN \
#   languagelearn-deploy

