# Use an official Ubuntu base image
FROM ubuntu:24.04

# Set environment variables
ENV DEBIAN_FRONTEND=noninteractive

# Update and install necessary packages
RUN apt-get update && apt-get install -y \
    curl \
    git \
    golang \
    postgresql \
    postgresql-contrib


# Install Node.js and npm using NodeSource
RUN curl -fsSL https://deb.nodesource.com/setup_lts.x | bash - && \
    apt-get update && \
    apt-get install -y nodejs && \
    apt-get clean

# Verify Node.js and npm installation
RUN node --version && npm --version

# Install the latest version of npm
RUN npm install -g npm@latest

# Clean up
RUN apt-get clean && rm -rf /var/lib/apt/lists/*

# Set the working directory and change ownership
WORKDIR /app

# Add build arguments
ARG SQUARE_LOCATION_ID
ARG SQUARE_APP_ID

# Build the UI
COPY client/ /app/client/
WORKDIR /app/client
RUN npm install
RUN REACT_APP_SQUARE_LOCATION_ID=${SQUARE_LOCATION_ID} REACT_APP_SQUARE_APP_ID=${SQUARE_APP_ID} npm run build

# Build the server
COPY server/ /app/server/
WORKDIR /app/server
RUN go mod download
RUN GOFLAGS=-buildvcs=false go build -o server

# Expose the default port
EXPOSE 8080

# Copy the database script and make it executable
WORKDIR /app
COPY db.sh /app/db.sh
COPY credits.sh /app/credits.sh
COPY prod.sh /app/prod.sh
RUN chmod +x /app/db.sh
RUN chmod +x /app/credits.sh
RUN chmod +x /app/prod.sh

# Change the CMD to use the startup script
CMD ["/app/prod.sh"]

# Docker build command to use:
#    docker build \
#    --build-arg SQUARE_LOCATION_ID=your_location_id \
#    --build-arg SQUARE_APP_ID=your_app_id \
#    -t languagelearn-deploy .
    
# Docker run command to use:
# docker run -d \
#   --name languagelearn \
#   --network host \
#   -v /path/to/local/dbdata:/var/dbdata \
#   -e OPENAI_SECRET_KEY \
#   -e GOOGLE_API_SECRET \
#   -e SQUARE_APP_ID \
#   -e SQUARE_LOCATION_ID \
#   -e SQUARE_ACCESS_TOKEN \
#   languagelearn-deploy

